import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import "./styles/programmes.scss";
import NextTopLoader from 'nextjs-toploader';
import Navigation from "@/components/common/Navigation";
import Footer from "@/components/common/Footer";
import MobileNav from "@/components/common/MobileNav";
import Newsletter from "@/components/common/Newsletter";

const poppins = Poppins({ weight: ['300', '400', '500', '600', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextTopLoader color="#7ABC25" showSpinner={false}/>
        <Newsletter />
        <Navigation />
        <MobileNav />
        {children}
        <Footer />
        <script
            type="text/javascript"
            id="hs-script-loader"
            async
            defer
            src="//js.hsforms.net/forms/v2.js"
          ></script>
        <script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/40083784.js"></script>
        </body>
    </html>
  );
}
