import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import "./styles/programmes.scss";
import NextTopLoader from 'nextjs-toploader';
import Navigation from "@/components/common/Navigation";

const poppins = Poppins({ weight: ['300', '400', '500', '600', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextTopLoader color="#7ABC25" showSpinner={false}/>
        <Navigation />
        {children}
        </body>
    </html>
  );
}
